/*
Copyright 2021 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

package annotation

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// Testee public test structure
type Testee struct {
	ID    int    `annotation:"TESTEE_ID"`
	Value string `env:"TESTEE_VALUE"`
}

func TestAnnotationParse(t *testing.T) {
	// arrange
	annotations := map[string]string{
		"my.com/id":      "1500",
		"my.com/name":    "Arnold",
		"my.com/surname": "Rimmer",
		"my.com/ranks":   "officer1,capitan,general,major",
		"my.com/armed":   "false",
	}
	type arnold struct {
		id      int      `annotation:"my.com/id, require=true"`
		name    string   `annotation:"my.com/name"`
		Surname string   `annotation:"my.com/surname, default=Schwarzenegger"`
		Ranks   []string `annotation:"my.com/ranks"`
		Armed   bool     `annotation:"my.com/armed,protected=true"`
	}
	// act
	tok := &arnold{Armed: true}
	err := Bind(annotations, tok)
	// assert
	assert.NoError(t, err)
	assert.Equal(t, true, tok.Armed)
}
